from typing import Protocol

from fourier_core.predefine import *


class DynalinkProtocol(Protocol):
    def to_dict(self) -> dict: ...

    def from_dict(self, dict_value=None) -> FunctionResult: ...

    def read_to_dict(self) -> dict: ...

    def read_from_dict(self, dict_value=None) -> FunctionResult: ...

    def write_to_dict(self) -> dict: ...

    def write_from_dict(self, dict_value=None) -> FunctionResult: ...
