from fourier_grx.task.menu import (
    TaskMenuRobotBase,
    TaskMenuRobotReal,
    TaskMenuGRX,
)


class GRXTaskCommand:
    TASK_IDLE = TaskMenuRobotBase.TASK_IDLE

    TASK_SERVO_ON = TaskMenuRobotReal.TASK_SERVO_ON
    TASK_SERVO_OFF = TaskMenuRobotReal.TASK_SERVO_OFF
    TASK_SERVO_REBOOT = TaskMenuRobotReal.TASK_SERVO_REBOOT
    TASK_CLEAR_FAULT = TaskMenuRobotReal.TASK_CLEAR_FAULT
    TASK_REMOTE_CONTROL = TaskMenuRobotReal.TASK_REMOTE_CONTROL

    TASK_SET_HOME = TaskMenuGRX.TASK_SET_HOME
    TASK_TEST_JOINT = TaskMenuGRX.TASK_TEST_JOINT_PD

    TASK_READY_STATE = TaskMenuGRX.TASK_APPLICATION_STAND_MOTION_CONTROL
    TASK_WALK = TaskMenuGRX.TASK_APPLICATION_WALK_MOTION_CONTROL
    TASK_RUN = TaskMenuGRX.TASK_APPLICATION_RUN_MOTION_CONTROL
    TASK_MOTION_BANK = TaskMenuGRX.TASK_APPLICATION_WALK_MOTION_BANK
    TASK_CLIMB_UP = TaskMenuGRX.TASK_APPLICATION_CLIMB_UP_MOTION_CONTROL
