from collections.abc import Callable
from enum import Enum
from typing import Any, Protocol

from fourier_core.predefine import *

from fourier_grx.predefine import *
from fourier_grx.fsm import *


class TaskProtocol(Protocol):
    def register(self, fsm_manager: FSMManager) -> FunctionResult: ...

    def add_task(self, task_type: TaskFunctionType) -> FunctionResult: ...

    def get_key(self) -> Enum: ...

    def get_name(self) -> str: ...

    def get_model(self) -> Any: ...

    def get_available(self) -> Callable | None: ...

    def get_on_activate(self) -> Callable | None: ...

    def get_on_deactivate(self) -> Callable | None: ...

    def get_on_enter(self) -> Callable | None: ...

    def get_on_exit(self) -> Callable | None: ...

    def get_on_tick(self, task_type: TaskFunctionType) -> Callable | None: ...

    def get_state(self) -> dict: ...

    def set_control(self, control: dict) -> FunctionResult: ...
