from enum import IntEnum


class RobotErrorCode(IntEnum):
    NONE = 0x00
    SHORT_CURCUIT = 0x01
    AMP_OVER_TEMP = 0x02
    AMP_OVER_VOLTAGE = 0x03
    AMP_UNDER_VOLTAGE = 0x04
    MOTOR_OVER_TEMP = 0x05
    FEEDBACK_ERROR = 0x06
    PHASING_ERROR = 0x07
    CURRENT_LIMIT = 0x08
    VOLTAGE_LIMIT = 0x09
    POSITIVE_POSITION_LIMIT = 0x0A
    NEGATIVE_POSITION_LIMIT = 0x0B
    TRACKING_ERROR = 0x0C
    POSITIION_WRAP = 0x0D
    USED_FOR_FAULTS_WITH_NO_OTHER_EMERGENCY = 0x0E
    NODE_GUARDING_ERROR = 0x0F
    COMMAND_ERROR = 0x10
    STO_FAULT = 0x11
