from fourier_grx.peripheral.fi_peripheral_joystick_interface import peripheral_joystick
from fourier_grx.peripheral.fi_peripheral_keyboard_interface import peripheral_keyboard

from fourier_grx.peripheral.fi_peripheral_virtual_joystick_interface import peripheral_virtual_joystick
from fourier_grx.peripheral.fi_peripheral_virtual_joystick import PeripheralVirtualJoystick

from fourier_grx.peripheral.fi_peripheral_virtual_teleoperation_interface import peripheral_virtual_teleoperation
from fourier_grx.peripheral.fi_peripheral_virtual_teleoperation import PeripheralVirtualTeleoperation

from fourier_grx.peripheral.fi_peripheral_virtual_keyboard_interface import peripheral_virtual_keyboard
from fourier_grx.peripheral.fi_peripheral_virtual_keyboard import PeripheralVirtualKeyboard

from fourier_grx.peripheral.fi_peripheral_virtual_mouse_interface import peripheral_virtual_mouse
from fourier_grx.peripheral.fi_peripheral_virtual_mouse import PeripheralVirtualMouse

from fourier_grx.peripheral.fi_peripheral_virtual_user_interface import peripheral_virtual_user
from fourier_grx.peripheral.fi_peripheral_virtual_user import PeripheralVirtualUser

from fourier_grx.peripheral.fi_peripheral_virtual_panel_interface import peripheral_virtual_panel
from fourier_grx.peripheral.fi_peripheral_virtual_panel import PeripheralVirtualPanel
